### PR TITLE
470 ga router pageview

### PR DESCRIPTION
**Pull request by lauraGgit**
## Summary
Resolves Issue #[470](https://github.com/18F/fs-open-forest-platform/issues/470)

*Describe the pull request here, including any supplemental information needed to understand it.*

## Impacted Areas of the Site
- analytics

## This pull request changes...
- [ ] expected change 1
- [ ] expected change 2

## This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### CODE REVIEW

**Comment by lauraGgit** [comment]
@mtlaney ok, pulled in through our ci. Looks like you've got a number of linting errors: https://circleci.com/gh/18F/fs-open-forest-platform/3450?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link, and all the e2es are broken. I believe you have been added to our github organization, so you should be able to now work off of this branch. If not, I'll be sure to go and add you.

**Comment by lauraGgit** [comment]
@mtlaney looks like we're still getting a linting error:

**Comment by mtlaney** [comment]
#519 fix for linting error. @lauraGgit @davemcorwin

**Comment by lauraGgit** [comment]
@davemcorwin this is the work I approved from @mtlaney but since I opened the PR, I cannot merge it, mine oking it?

**Pull request merged**
