### PR TITLE
Open Forest Branding on the site 

### PR DESCRIPTION
**Pull request by lauraGgit**
## Summary
Resolves Issue #[183](https://github.com/18F/fs-open-forest-platform/issues/183)

*Describe the pull request here, including any supplemental information needed to understand it.*

## Impacted Areas of the Site
- Frontend
- Christmas Trees
- Special Use
- Emails

## This pull request changes...
- [X] Update angular title service to include u.s. open forest reference
- [x]  Update headers to include ref to open forest
- [x] additional copy changes to include Open Forest

## This pull request is ready to merge when...
- [x] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [x] The change has been documented
  - [x] Associated OpenAPI documentation has been updated

### CODE REVIEW

**Comment by lauraGgit** [comment]
@annepetersen is this meta-data look alright? 
<meta name="Description" content="Open Forest is lets help apply for and purchase permits with the United States Forest Service.">
<meta name="Keywords" content="Forest Service, permitting, permits, special uses, christmas trees">

The titles are already updated.

**Comment by annepetersen** [comment]
The description should be a complete sentence, which I'm not sure that one is. Maybe:

 <meta name="Description" content="Use Open Forest to apply for and purchase permits with the United States Forest Service.">

Descriptions should also be unique per public page, so we'll have to look at each one.

And the keywords should be words people search for. Would anyone search for "special uses," do we think? And should we add "national forests" and similar variations?

> <meta name="Keywords" content="Forest Service, permitting, permits, special uses, christmas trees">
> ```

**Comment by lauraGgit** [comment]
Ok, that makes sense - for the description - should it be additive like `base sentence + unique to that page` or just `unique to that page`? And i can go ahead and add the `national forests, national forest` and remove special uses.

**Comment by annepetersen** [comment]
If possible, just `unique to that page`. That said, the base info should be available throughout, so if the most efficient way to get that in there is to do `base sentence + unique to that page`, that's fine. Sounds good on keywords. Thanks!

**Comment by annepetersen** [comment]
Looks terrific!

**Comment by lauraGgit** [comment]
@annepetersen while we can set the forestName for the title, it looks like the `meta` service in angular will break on adding in the forestName slug. Are you ok with us just putting in `your national forest` for the meta description on the xmas forest info page and the xmas and on the xmas new application page? the title will have the forest name in it.

**Pull request merged**
