### PR TITLE
fix sidenav issue add server/yarn.lock to gitignore

### PR DESCRIPTION
**Pull request by mtlaney**
## Summary
Resolves Issue #[331](https://github.com/18F/fs-open-forest-platform/issues/331)

Corrected sidenav overlapping issues on christmas-trees/forests pages

## Impacted Areas of the Site
UI sidebar area of christmas-trees/forests

## This pull request changes...
- [ ] sidebar scrolling behavior should not overlap breadcrumbs

## This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### CODE REVIEW

**Comment by lauraGgit** [comment]
When the season is `open`. i.e. you have changed the season date to be before today's date in the admin screen and the user can now see the buy permit buttons, the overlap still occurs (when tested locally)

image

**Comment by mtlaney** [comment]
@lauraGgit Changing season dates makes no difference on the buying permit portion for me. 

screen shot 2018-09-07 at 9 55 33 am
screen shot 2018-09-07 at 9 57 27 am

**Comment by lauraGgit** [comment]
I was having a weird issue with the Arapahoe season dates opening which might be worth investigating in and of itself. Can you try for the mt hood?

**Comment by mtlaney** [comment]
You're right, I can see the bug in Mt. Hood but not Arapahoe. I'll fix overlap here than dig into why Arapahoe dates are posting to one page but not rendering on the other

**Comment by lauraGgit** [comment]
@mtlaney I'm asking @msadakFS to help verify this. I think i may be because the ARP has district specific cutting dates and the others do not, but we may have to open a separate ticket to address this bug.

**Comment by lauraGgit** [comment]
I just checked on our staging and that does seem to be correct. @mtlaney can you take a screenshot of what you see for `admin/christmas-trees/district-dates`?

**Comment by mtlaney** [comment]
screen shot 2018-09-07 at 10 18 32 am

**Comment by msadakFS** [comment]
Seems like the issue started with the season cutting dates and then evolved to change cutting area dates. @mtlaney What exactly is the issue with the cutting area dates page?

**Comment by mtlaney** [comment]
@msadakFS no issue that I can see with the cutting area dates page. Arapahoe season dates is not changing the Christmas-tree permit page locally, but is on the dev server

**Comment by adborden** [comment]
@lauraGgit asked me to take a look at this. I'm not sure I'm following the conversation but I'm still getting some overlap with the sidebar. I think the problem is that the offsets assume there's no content in the scroll container above the sidebar, but there is (the breadcrumb). I think you want to tweak the if condition so that the scroll happens later.. alternatively we could tweak the scroll container. Using `#skip-nav-target` makes the calculation much simpler.

**Comment by mtlaney** [comment]
@lauraGgit please check latest push. Corrected spacing for when buy permit option is available as well.

**Pull request merged**
