### PR TITLE
Add context for phone number

### PR DESCRIPTION
**Pull request by suprenant**
Add "General information phone:" to phone number so users know they are getting a general phone line

Remove bold styling to match other styles

This is a change that resulted from this ticket, originally:
 - https://trello.com/c/vFRsaeSi/971-customer-support-and-help-desk-plan-frontliner-coordination

## This pull request is ready to merge when...
- [ ] Tests have been updated (and all tests are passing)
- [ ] This code has been reviewed by someone other than the original author
- [ ] The change has been documented
  - [ ] Associated OpenAPI documentation has been updated

### CODE REVIEW

**Comment by suprenant** [comment]
This is my first PR on this engagement. Please let me know if you have any suggested changes to the code or process.

**Comment by lauraGgit** [comment]
@suprenant could you please put the base of this PR to `dev` and in the future would you mind changing your branch name to start with the number of the issue you are working off of?

**Comment by suprenant** [comment]
@lauraGgit:
 - _Base of this PR to dev_ – yes, I will do that
 - _Changing your branch name to start with the number of the issue you are working off of_ – yes. What is our practice if we are making a change for which there is no specific issue?

**Comment by lauraGgit** [comment]
We try to tie our prs to issues so that there is better traceability to the roadmap. But for those cases when we do not, we just name it what it's action is.

**Comment by lauraGgit** [comment]
Also pulling in @annepetersen for a content check!

**Comment by lauraGgit** [comment]
But also realizing this is part of practice that has evolved out of step of our documentated gitflow: https://github.com/18F/fs-open-forest/wiki/How-we-work#project-gitflow

**Comment by suprenant** [comment]
@lauraGgit OK, I updated the base branch to dev. I think that makes us good to go here given we don't have a related issue for this in GitHub, but if anything else is needed, please let me know.

**Comment by annepetersen** [comment]
Late to this, but @suprenant, could we just use "general information:" rather than "general information phone:"? For a screenreader, the number being read (especially when it begins with 800-) makes it clear it's a phone number, and for those that can see the screen, the number is easy to recognize as a phone number. Most phone numbers I see in footers don't include "phone" in the label.

**Comment by suprenant** [comment]
@annepetersen thanks for your feedback. Sure thing – I opened a new PR for this here: https://github.com/18F/fs-open-forest-platform/pull/444

**Comment by lauraGgit** [comment]
Ah the other reason we create issues associated for PR's is that they are easier to track for the PO - as they move from merged into dev and PO ok to go to staging.

**Pull request merged**
