### PR TITLE
550 store permit purchase date

### PR DESCRIPTION
**Pull request by briandavidson**
﻿## Summary
Addresses Issue # 550

Please note if fully resolves the issue per the acceptance criteria: Y

*Describe the pull request here, including any supplemental information needed to understand it.*
We want to be able to keep track of a permit's purchase date without using the 'updatedAt' field which does not necessarily reflect the purchase date accurately.

## Impacted Areas of the Site
- /admin/christmas-trees/reports

## This pull request changes...
- [x] the 'issue date' of a permit to use the new 'purchaseDate' column

## This pull request is ready to merge when...
- [x] Feature branch is starts with the issue number
- [x] Is connected to its original issue via zenhub 👇
- [x] Tests have been updated 
- [x] All tests are passing and meet coverage, linting, and accessibility requirements. And no security vulnerabilities ⚫️(Circle)
- [x] Server actions captured by logs (manual)
- [x] Documentation / readme.md updated (manual)
- [x] API docs updated if need (manual)
- [x] JSDocs updated (manual)
- [x] This code has been reviewed by someone other than the original author
- [ ] The migration has been tested on `staging` successfully.

### CODE REVIEW

**Comment by briandavidson** [comment]
@mtlaney / @davemcorwin this is ready for a code review.

**Comment by briandavidson** [comment]
Thanks for the review Dave!

> 1. The query used to populate the admin reports is still using the updatedAt date:
>    https://github.com/18F/fs-open-forest-platform/blob/550-store_permit_purchase_date/server/src/controllers/christmas-tree/admin.es6#L88

I've updated this query to use `purchaseDate` instead of `updatedAt`. Should be all set now.

> 2. The tests in `christmas-trees-admin-controller.spec.es6` were not updated to use the purchase date. This is concerning since the checkbox for `Tests have been updated` is checked...

Before making the change to the query all the existing tests were passing. I mistakenly took this to mean that there were no tests to update, but after making the change there were two tests that started failing. I went ahead and updated them accordingly and they are ready for you to take another look at.

> 3. Is there a plan for migrating over the data? I don't see anything in the migration file that will do it and if there is a separate plan it should be documented in the PR or linked to if it exists elsewhere.

 I read through http://docs.sequelizejs.com/manual/migrations.html but am still not entirely clear what else needs to happen in the migration file. If you have any clues to get me started, or if you have time to pair up, it'd be much appreciated!

**Comment by briandavidson** [comment]
@davemcorwin this is ready for a re-review

**Comment by briandavidson** [comment]
@davemcorwin what's our process for the refactoring work? You said it could be done in a subsequent PR -  would it be a PR for this same issue, or would a new issue be created for the refactoring work?

**Comment by davemcorwin** [comment]
Create a separate issue

**Pull request merged**
